### ISSUE TITLE
Unclear error in settings page

### ISSUE THREAD

**Issue by dasyad00** [CosmosTUe/Cosmos#72]
**Describe the bug**
Invalid User and Profile forms inform the user with the text "Please correct the error below" without further explanations as to what is required.

**To Reproduce**
1. Create server super user (has empty user and profile fields)
2. Login as server super user
3. Open profile settings
4. Press "Save"

**Expected behavior**
User should be informed more clearly as to what needs to be done to fix the error.

**Environment:**
 - OS: Linux
 - Browser: Firefox 81.0.2

**Comment by bcvandendool** [comment]
As this only happens to the admin account and that is only used by us, this is no big issue. Furthermore adding code for this one exception that needs to be maintained seems like a waste.
