### ISSUE TITLE
Make Secure Cookie settings a secrets.json variable

### ISSUE THREAD

**Issue by maximekabel** [CosmosTUe/Cosmos#93]
**Is your feature request related to a problem? Please describe.**
Right now the Secure cookie setting is always set to true in the django settings. With it on it's not possible to log in as admin as the cookie will be invalid.

**Describe the solution you'd like**
Change this into an environment variable for the secrets.json file

Make the following an env variable
```
SESSION_COOKIE_SECURE
CSRF_COOKIE_SECURE
```

**Additional context**
This is to make setting up a dev env easier.

**Comment by bcvandendool** [comment]
Can you detail what steps you took to try to login as admin? As the issue is not reproducible on my side.

**Comment by bcvandendool** [comment]
Has been fixed
